### ============================================= ПОЛЬЗОВАТЕЛИ ===================================================

### Регистрация пользователя 1
POST http://localhost:3330/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "mikhail@sakharov.com",
  "firstName": "mikhail",
  "lastName": "sakharov",
  "password": "123456"
}

### Регистрация пользователя 2
POST http://localhost:3330/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "qwe@asd.com",
  "firstName": "qwe",
  "lastName": "asd",
  "password": "123456"
}

### Получение детальной информации по id
GET http://localhost:3330/api/auth/63c5009dd38125d3ead28f1d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M1MDA5YWQzODEyNWQzZWFkMjhmMTkiLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3ROYW1lIjoibWlraGFpbCIsImxhc3ROYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM4NTUxODcsImV4cCI6MTY3Mzg1NTU0N30.jLDL8npT4U02iByY4_N-d91tNFwvNIg6VTQYCDatrDA

### Авторизация
POST http://localhost:3330/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "mikhail@sakharov.com",
  "password": "123456"
}

### Подписка на пользователя
POST http://localhost:3330/api/auth/63c5009dd38125d3ead28f1d/subscription HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M1MDA5YWQzODEyNWQzZWFkMjhmMTkiLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3ROYW1lIjoibWlraGFpbCIsImxhc3ROYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM4NTUxODcsImV4cCI6MTY3Mzg1NTU0N30.jLDL8npT4U02iByY4_N-d91tNFwvNIg6VTQYCDatrDA

### =============================================== ПУБЛИКАЦИИ ===================================================

### Запрос публикаций
GET http://localhost:3331/api/posts HTTP/1.1

### Запрос своих черновиков
GET http://localhost:3331/api/drafts HTTP/1.1

### Запрос с сортировкой по лайкам
GET http://localhost:3331/api/posts?sortType=likes HTTP/1.1

### Запрос с сортировкой по комментам
GET http://localhost:3331/api/posts?sortType=comments HTTP/1.1

### Запрос публикаций (пагинация)
GET http://localhost:3331/api/posts?page=3&postsCount=3 HTTP/1.1

### Запрос с параметром authorId
GET http://localhost:3331/api/posts?authorId=6398ab2b5a6c4e3fefe83773 HTTP/1.1

### Запрос с параметром tag
GET http://localhost:3331/api/posts?tag=ert HTTP/1.1

### Запрос с параметром type
GET http://localhost:3331/api/posts?type=quote HTTP/1.1

### Редактирование публикации
PATCH http://localhost:3331/api/posts/58 HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "isPublished": true,
  "content": {
    "title": "fgh",
    "announcement": "hjk",
    "text": "vbn"
  },
  "tags": ["ttt", "yyy", "uuiii"],
  "authorId": "6398ab2b5a6c4e3fefe83771"
}

### Удаление публикации
DELETE http://localhost:3331/api/posts/145 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M1MDA5YWQzODEyNWQzZWFkMjhmMTkiLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3ROYW1lIjoibWlraGFpbCIsImxhc3ROYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM4NTkxNzUsImV4cCI6MTY3Mzg1OTUzNX0.jVc_O9hWww6qfywub7OxeiPHBlDeylYTyk-ClkYUdYw

### Лайк
PATCH http://localhost:3331/api/posts/146/like HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M1MDA5YWQzODEyNWQzZWFkMjhmMTkiLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3ROYW1lIjoibWlraGFpbCIsImxhc3ROYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM4NjMwMDEsImV4cCI6MTY3Mzg2MzM2MX0.h9fAXtYQLRlcQmcnpx4JQS5Virsyvk88MxSafkmDaeM

### Репост публикации
POST http://localhost:3331/api/posts/repost/146 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M1MDA5YWQzODEyNWQzZWFkMjhmMTkiLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3ROYW1lIjoibWlraGFpbCIsImxhc3ROYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM4NTg0NzQsImV4cCI6MTY3Mzg1ODgzNH0.MOXHQzZfBV9usVzI9vm-u4bZswOELnU7VXDgfsm3mUg

### Создание публикации типа video
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M1MmVjMWU0MGQyM2RkZDIyOGE5MTciLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3ROYW1lIjoibWlraGFpbCIsImxhc3ROYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM4Nzk4MDksImV4cCI6MTY3Mzg4MDE2OX0.VxuxY0B3PtV0cI-ZYuPMv1ALlQw1_RXpo-TML26fluM

{
  "type": "video",
  "isPublished": true,
  "content": {
    "videoTitle": "Chill Music Lab Chill Music Lab Chill Music Lab",
    "videoUrl": "https://www.youtube.com/watch?v=Q7t4JOt-KH4"
  },
  "tags": ["qwe", "asd", "zxc"]
}

### Создание публикации типа text
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M1MmVjMWU0MGQyM2RkZDIyOGE5MTciLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3ROYW1lIjoibWlraGFpbCIsImxhc3ROYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM4NzM4MzYsImV4cCI6MTY3Mzg3NDE5Nn0.TNn1uBE5DugmoGdmB6pk0ACJAB_jAdG71jg-_9nvzYg

{
  "type": "text",
  "isPublished": true,
  "content": {
    "textTitle": "",
    "textAnnouncement": "",
    "text": ""
  },
  "tags": ["qwe", "ert", "zxc"]
}

### Создание публикации типа quote
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "quote",
  "isPublished": true,
  "content": {
    "quoteText": "",
    "quoteAuthor": ""
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "6398ab2b5a6c4e3fefe83771"
}

### Создание публикации типа photo
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "photo",
  "content": {
    "image": ""
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "6398ab2b5a6c4e3fefe83771"
}

### Создание публикации типа link
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M1MmVjMWU0MGQyM2RkZDIyOGE5MTciLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3ROYW1lIjoibWlraGFpbCIsImxhc3ROYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM4Nzg3NzUsImV4cCI6MTY3Mzg3OTEzNX0.lJ4uzPL4N75nJICM4JQQ-PGGDz62EmkCdZjrFtp9cbI

{
  "type": "link",
  "content": {
    "linkUrl": "https://www.npmjs.com/package/class-validator#validation-decorators",
    "linkDescription": "linkDescription"
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "6398ab2b5a6c4e3fefe83771"
}

### =============================================== КОММЕНТАРИИ ==================================================

### Добавление комментария
POST http://localhost:3331/api/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M1MDA5YWQzODEyNWQzZWFkMjhmMTkiLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3ROYW1lIjoibWlraGFpbCIsImxhc3ROYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM4NTkxNzUsImV4cCI6MTY3Mzg1OTUzNX0.jVc_O9hWww6qfywub7OxeiPHBlDeylYTyk-ClkYUdYw

{
  "text": "Comment text",
  "postId": 145
}

### Получение комментариев к публикации
GET http://localhost:3331/api/comments/58 HTTP/1.1

### Получение комментариев к публикации (пагинация)
GET http://localhost:3331/api/comments/60?page=1&commentsCount=1 HTTP/1.1

### Получение комментариев к публикации с параметром commentsCount
GET http://localhost:3331/api/comments/32?commentsCount=3 HTTP/1.1

### Удаление комментария
DELETE http://localhost:3331/api/comments/12 HTTP/1.1
